<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- NuGet packaging properties -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Edgamat.Messaging</PackageId>
    <Version>1.0.1</Version>
    <Authors>edgamat</Authors>
    <Company>Edgamat</Company>
    <Description>Small .NET library exposing a message-consumer contract for Azure Service Bus hosts.</Description>
    <PackageTags>messaging;servicebus;azure;consumer;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/edgamat/Edgamat.Messaging</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/edgamat/Edgamat.Messaging</PackageProjectUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.12.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

</Project>
